# .scrutinizer.yml
build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
            project_setup:
                override: true
            tests:
                override:
                - php-scrutinizer-run
filter:
    excluded_paths:
        - '_archive/*'
        - 'tests/*'
tools:
    external_code_coverage:
        timeout: 300    # Timeout in seconds.
