language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
