language: php

php:
- 7.1
- 7.2
- 7.3
- 7.4snapshot

matrix:
  allow_failures:
  - php: 7.4snapshot

install:
- composer install
- wget https://github.com/diff-sniffer/git/releases/download/0.2.0/git-phpcs.phar

script:
- vendor/bin/phpunit
- php git-phpcs.phar $TRAVIS_COMMIT_RANGE

after_script:
- if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
