name: CI

on: [push, pull_request]

jobs:
  phpunit-7-1:
    strategy:
      fail-fast: false
      matrix:
        php_version: ["7.1", "7.4"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - name: Unit Tests with PHPUnit 7.1
        run: vendor/bin/phpunit --stderr --version 7.1

  phpunit-9-6:
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.1"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - name: Unit Tests with PHPUnit 9.6
        run: vendor/bin/phpunit --stderr --version 9.6
